export enum STRINGS {
	EMAIL_CONOR = 'Conor@GatesKennedy.com',
	GITHUB_GK = 'https://github.com/GatesKennedy',
	LINKEDIN_CONOR = 'https://linkedin.com/in/conorgateskennedy',
	SPOTIFY_ONO = 'https://open.spotify.com/user/ohnodamn',
	INTAKE_DEMO = 'https://intakedemo.gateskennedy.com',
	RMH_LINK = 'https://www.newestech.com/modern-suite-software/',
	ESC_LINK = 'https://esccollective.com/',
	FASTIFY_REPO = 'https://github.com/GatesKennedy/SEED-FastifyAPI',
	K6_REPO = 'https://github.com/GatesKennedy/SEED-FastifyAPI',
	GK_HELLO_REPO = 'https://github.com/GatesKennedy/GK_Hello_Next13',
}

export enum ATTRIBUTE_TITLE {
	TIME = 'Time: ',
	TECH = 'Tech: ',
	DUTY = 'Duty: ',
	STATUS = 'Status: ',
}

export enum STATUS_TYPE {
	IN_PROGRESS = 'In Progress',
	OPEN = 'Open (ongoing)',
	CLOSED = 'Closed',
	INCOMPLETE = 'Abandoned',
}

export enum TOOL {
	AGILE = 'Agile Methodology',
	AGILE_SCRUM = 'Agile & Scrum',
	ATLASSIAN = 'Jira & Confluence',
	AUTOGEN = 'AutoGen AI Agents',
	AWS = 'AWS',
	AWS_CLI = 'AWS CLI',
	AWS_DYNAMO = 'AWS DynamoDB',
	AWS_EC2 = 'AWS EC2',
	AWS_LAMBDA = 'AWS Lambda',
	AWS_PIPE = 'AWS CodePipeline',
	AWS_S3 = 'AWS S3 Buckets',
	AWS_RDS = 'AWS RDS',
	AWS_ROUTE = 'AWS Route 53',
	AXIOS = 'Axios',

	BASH = 'BASH',

	C_SHARP = 'C#',
	CHAKRA = 'Chakra UI',
	CHART_JS = 'Chart.js',
	CONDA = 'Conda / Mamba',
	CONFLUENCE = 'Confluence',
	CORS = 'CORS',
	CSS = 'CSS',

	D3 = 'D3.js',
	DATA_VIS = 'Data Visualization',
	DAY_JS = 'Day.js',
	DB_DESIGN = 'DB Design',
	DB_MIGRATE = 'DB Migrations',
	DJANGO = 'Django',
	DOCKER = 'Docker Containers',
	DOCKER_HUB = 'Docker Hub',
	DOCKER_COMPOSE = 'Docker-Compose',
	DOT_NET = '.NET',

	ESLINT = 'ESLint',
	EXPRESS = 'Express.js (TS)',
	FAST_API = 'FastAPI (Python)',
	FASTIFY = 'Fastify',

	GIT = 'Git',
	GIT_HUB = 'GitHub',
	GIT_LAB = 'GitLab',
	GO = 'GoLang',
	GRAPH_QL = 'GraphQL API',
	GREEN_GEEKS = 'GreenGeeks',

	HASURA = 'Hasura',
	HEROKU_PIPE = 'Heroku Pipelines',
	HTML = 'HTML',
	HTML_CSS = 'HTML & CSS',
	HTTPS = 'HTTPS',
	HUGGING = 'Hugging Face',

	JENKINS = 'Jenkins',
	JIRA = 'Jira',
	JWT = 'JSON Web Tokens',
	K6 = 'Grafana K6',
	LINUX = 'Linux OS',
	LLAMA = 'LLaMA LLM',
	LocalLLMs = 'Local LLMs',

	MUI = 'Material UI',
	MONGO = 'MongoDB',
	MOCHA = 'MochaJS',
	MY_SQL = 'MySQL',

	NEXT = 'Next.js (TS)',
	NEXTAUTH = 'NextAuth.js',
	NGINX = 'NGINX',
	NGROK = 'NGROK',
	NODE = 'Node.js (TS)',
	NODEMAILER = 'Nodemailer',
	NODE_POSTGRES = 'Node-Postgres',
	NIVO = 'Nivo Charts',
	NUMPY = 'NumPy',

	OPENSSL = 'OpenSSL',
	OAUTH = 'OAuth 2.0',

	PANDAS = 'Pandas',
	PM2 = 'PM2',
	POSTGRES = 'PostgreSQL',
	POSTMAN = 'Postman',
	POWERSHELL = 'PowerShell',
	PRISMA = 'Prisma ORM',
	PUPPETEER = 'Puppeteer',
	PWA = 'Progressive Web App',
	PYTHON = 'Python 3',
	PYDANTIC = 'Pydantic',

	REACT = 'ReactJS (TS)',
	REACTHOOKFORM = 'React Hook Form',
	REDIS = 'Redis',
	REDUX = 'Redux',
	REST = 'RESTful API',
	RAILWAY = 'Railway',

	SAML = 'SAML',
	SASS = 'SASS',
	SCRUM = 'Scrum Methodology',
	SEQUELIZE = 'Sequelize ORM',
	SOCKET_IO = 'SocketIO',
	SSH = 'SSH',
	SSL = 'Secure Socket Layer (SSL)',
	STYLED_COMP = 'Styled Components',
	SQL_SERVER = 'SQL Server',
	SQL_ALCH = 'SQLAlchemy',
	SMTP = 'SMTP',

	TEAM_CITY = 'TeamCity',
	TS = 'TypeScript',
	TMUX = 'tmux',
	VIM = 'Vim',
	WEB_SOCKETS = 'Web Sockets',
	YAML = 'YAML',
	ZSH = 'ZSH',
}
